# Generated by Django 2.0.4 on 2018-04-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authot',
            new_name='author',
        ),
    ]
